services:
  kamailio-base:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DISTRO_IMAGE: ${DISTRO_IMAGE}
        KAMAILIO_VERSION: ${KAMAILIO_VERSION:-58}
        STARTER_KAM_USER: ${STARTER_KAM_USER:-kamailio}
        STARTER_KAM_GROUP: ${STARTER_KAM_GROUP:-kamailio}
    container_name: kamailio-base
    hostname: kamailio-base
    tty: true
    privileged: true
    platform: linux/amd64
