services:
  kamailio-base:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DISTRO_IMAGE: ${DISTRO_IMAGE}
        KAMAILIO_VERSION: ${KAMAILIO_VERSION:-58}
        STARTER_KAM_USER: ${STARTER_KAM_USER:-kamailio}
        STARTER_KAM_GROUP: ${STARTER_KAM_GROUP:-kamailio}
    container_name: kamailio-base
    hostname: kamailio-base
    tty: true
    privileged: true
    platform: linux/amd64

  kamailio:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DISTRO_IMAGE: ${DISTRO_IMAGE}
        KAMAILIO_PACKAGES: ${KAMAILIO_PACKAGES}
        KAMAILIO_VERSION: ${KAMAILIO_VERSION:-58}
        STARTER_KAM_USER: ${STARTER_KAM_USER:-kamailio}
        STARTER_KAM_GROUP: ${STARTER_KAM_GROUP:-kamailio}
        TMP_FILE_LOCATION: ${TMP_FILE_LOCATION:-/var/run/kamailio}
    container_name: kamailio
    hostname: kamailio
    environment:
      - SHM_MEMORY=${SHM_MEMORY:-128}
      - PKG_MEMORY=${PKG_MEMORY:-16}
      - CONFIGS_FOLDER=${CONFIGS_FOLDER:-/etc/kamailio}
      - CFGFILE=${CFGFILE:-main.cfg}
      - STARTER_KAM_USER=${STARTER_KAM_USER:-kamailio}
      - STARTER_KAM_GROUP=${STARTER_KAM_GROUP:-kamailio}
      - TMP_FILE_LOCATION=${TMP_FILE_LOCATION:-/var/run/kamailio}
      - LOG_FILE_DIR=${LOG_FILE_DIR:-/var/log/kamailio}
      - LOG_FILE_NAME=${LOG_FILE_NAME:-kamailio.log}
      - DB_CONNECTION=${DB_CONNECTION}
      - MAX_EXPIRES=${MAX_EXPIRES}
      - LISTEN_IP=${LISTEN_IP}
      - HEPLIFY_IP=${HEPLIFY_IP}
      - HEP_CAPTURE_ID=${HEP_CAPTURE_ID}
    volumes:
      - ./configs:${CONFIGS_FOLDER}
      - ./logs:${LOG_FILE_DIR}
    ports:
      - "5060:5060"
    networks:
      - common-network
      - all_in_one
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    tty: true
    privileged: true
    platform: linux/amd64

networks:
  common-network:
    external: true
  all_in_one:
    external: true
    name: all-in-one_default  # Ensure this matches the actual name of the existing network
